export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  adminEmail: process.env.ADMIN_EMAIL ?? "",
  adminPassword: process.env.ADMIN_PASSWORD ?? "",
  adminName: process.env.ADMIN_NAME ?? "LE BRIEF Admin",
  searchConsoleClientEmail: process.env.SEARCH_CONSOLE_CLIENT_EMAIL ?? "",
  searchConsolePrivateKey: process.env.SEARCH_CONSOLE_PRIVATE_KEY ?? "",
  searchConsolePrivateKeyId: process.env.SEARCH_CONSOLE_PRIVATE_KEY_ID ?? "",
  searchConsoleProperty: process.env.SEARCH_CONSOLE_PROPERTY ?? "https://www.lebrief.energy/",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
};
