name: Daily Newsletter Draft

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  generate-daily-newsletter-draft:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger LE BRIEF daily newsletter draft
        run: |
          curl --fail --show-error --silent \
            "https://www.lebrief.energy/api/cron/newsletter-daily-draft"
